Update Font Awesome to v6.4.2
LMMS/lmms.io pull request #370
Opened 2023-08-31 22:26 UTC by Panquesito7

Things added/changed:

- Update Font Awesome to v6.4.2.
  - Closes #365.

2023-09-01 16:33 UTC, DomClark requested changes

2023-09-01 16:33 UTC, DomClark commented on forum/style/template/overall_footer.html
> -				<!-- IF S_MERGE_VIEW -->
These aren't normal HTML comments, but rather phpBB template tags. Converting them to JavaScript comments will break the template. You'll need to revert all changes to this file.

2023-09-02 21:09 UTC, DomClark approved these changes

2024-01-29 19:25 UTC, Panquesito7 commented
Bump.

2024-02-13 03:43 UTC, tresf commented
@Panquesito7 sorry for the delay on this.  Did you test this locally?  I just don't want to merge and add any major regressions (or at least have someone on the switch if some arise).  I'm just not sure how backwards compatible the icon names are.

2024-02-14 20:13 UTC, Panquesito7 commented
> @Panquesito7 sorry for the delay on this. Did you test this locally? I just don't want to merge and add any major regressions (or at least have someone on the switch if some arise). I'm just not sure how backwards compatible the icon names are.

Sure, no worries. Just tested it right now using [Gitpod](https://www.gitpod.io) and everything seems to be perfectly fine (at least on the main page). If you want to test it more easily, you can use Gitpod as well and run the necessary commands to compile and run the website online.

Updated (this PR).
![image](https://github.com/LMMS/lmms.io/assets/51391473/cb9a5c8d-1625-4dfc-a439-69dfc3f967fd)

Old (current).
![image](https://github.com/LMMS/lmms.io/assets/51391473/1bf0a1c3-8fba-486d-bebe-5ce799bae866)

2024-02-14 21:22 UTC, merged